# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Building Require-Checker phar"

on:
    pull_request:
#    release:
#      types: [published]

jobs:
    build:
        name: "Building Require-Checker phar"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "7.4"
                    - "8.0"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  tools: "phing"
                  coverage: "none"
                  php-version: ${{ matrix.php-version }}
                  ini-values: memory_limit=-1, phar.readonly=0

            - name: "Install prod dependencies"
              run: "composer update --no-interaction --no-progress --no-suggest --no-dev"

            - name: "Build phar file via phing"
              run: "phing phar-build"

            - name: "Sign Phar"
 #             if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
              run: |
                echo "$PRIVATE_KEY" > privatekey.pem
                openssl dgst -sha512 -sign privatekey.pem -out build/composer-require-checker.phar.asc build/composer-require-checker.phar
              env:
                PRIVATE_KEY: ${{ secrets.SIGNING_SECRET_KEY }}

            - name: "Upload phar file artifact"
              uses: actions/upload-artifact@v2
              with:
                  name: composer-require-checker-${{ matrix.php-version }}.phar
                  path: |
                    build/composer-require-checker.phar
                    build/composer-require-checker.phar.asc
